### ISSUE TITLE
Simpler installation method

### ISSUE THREAD

**Issue by patch-work** [jantari/LSUClient#104]
**Describe the problem**

```
$updates = Get-LSUpdate | Where-Object { $_.Installer.Unattended }
$updates | Save-LSUpdate -Verbose
$updates | Install-LSUpdate -Verbose
```

The above method to install updates is not compatible with powershell oneliners.

Example: 

```
> ssh -f -n -q 192.168.1.14 'powershell -nologo -noprofile Get-LSUpdate'

ID              Title                                    Type     ReleaseDate           Version      Severity
--              -----                                    ----     -----------           -------      --------
m4gfw2330m_corp Intel Management Engine Firmware - 10/11 Firmware 6/12/2024 12:00:00 AM 16.1.30.2330 Recommended
```

```
> ssh -f -n -q 192.168.1.14 'powershell -nologo -noprofile Get-LSUpdate | Save-LSUpdate -Verbose'

'Save-LSUpdate' is not recognized as an internal or external command, operable program or batch file.
```

**Describe the solution you'd like**

`Get-LSUpdate -Install -Unattended -Verbose`

**Describe alternatives you've considered**

**Additional context**

**Comment by jantari** [comment]
I believe the error you are getting is because the command:

    'powershell -nologo -noprofile Get-LSUpdate | Save-LSUpdate -Verbose'

gets run in the cmd shell (by default) on the remote computer  ([See Microsoft Docs](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration#configuring-the-default-shell-for-openssh-in-windows)), so cmd will run `powershell -nologo -noprofile Get-LSUpdate` and then  interpret the pipe character (`|`) rather than pass it to powershell.exe, and then attempt to run a  cmd-command called `Save-LSUpdate` which doesn't exist.

You have to quote the powershell-command appropriately or find a different method like setting powershell as the default shell used by OpenSSH, Base64-encoding the commands and using powershell.exe -EncodedCommand, or storing your commands in a script file and then running that.

Try:

    ssh -f -n -q 192.168.1.14 'powershell -NoLogo -NoProfile -Command "Get-LSUpdate | Save-LSUpdate -Verbose"'

**Comment by patch-work** [comment]
I think the problem is the unnecessarily convoluted method to call the installer.

**Comment by jantari** [comment]
The operations of Getting, Saving and Installing updates are intentionally split into multiple cmdlets.

This is the documented PowerShell best-practice / recommendation:

> The verb part of the name identifies the action that the cmdlet performs. The noun part of the name identifies the entity on which the action is performed

Source: https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.4

and also happens to align with the Unix philosophy principle 1, which has influenced all command-line tools' design for the last 46 years and counting:

> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".

Source: https://en.wikipedia.org/wiki/Unix_philosophy#Origin

Splitting the duties into multiple cmdlets also affords the users of the module more control and flexibility, which is a major feature of LSUClient and PowerShell in general.

You will have to find a way to make it work as-is, or not use LSUClient, because the way it is currently is the better way. A cmdlet design like `Get-LSUpdate -Install -Unattended -Verbose` would be _very_ bad and to my knowledge the only module that works like that is PSWindowsUpdate. Note how there is no `Get-ChildItem -Remove` in PowerShell either.

I hope this answers your question, but I will not update the cmdlets in the way you proposed for the above reasons.
