### ISSUE TITLE
USBC_FW_V373.exe Error

### ISSUE THREAD

**Issue by alexecooper** [jantari/LSUClient#15]
Hi,

Not sure if it's just my machine (Lenvo T408s) but when I run $downloads = Get-LSUpdate | Where-Object { $_.Installer.Unattended } after a few mins, I get an error 
![Capture](https://user-images.githubusercontent.com/27003428/76409769-c16af080-6386-11ea-9960-e0cad4db1edb.PNG) - USBC_FW_V373.exe

Looking at the Task Manager, it seems to be fusbcd05_version.exe (in the users appdata temp directory) causing this. It's not a major issue as clicking OK, seems to continue but annoying nonetheless. 
![Capture2](https://user-images.githubusercontent.com/27003428/76410061-39391b00-6387-11ea-8e52-3628f3e410df.PNG)

**Comment by jantari** [comment]
I am able to reproduce this on L490 notebooks.

Not sure why it can't find that file though, `usbc_fw_v373.exe` is in the same folder.

This issue is actually quite important because it causes unattended execution to hang indefinitely...

**Comment by jantari** [comment]
Hi, could you try this again with the latest changes on the master branch?

I've tested 4 notebooks so far and I think I've fixed it.

**Comment by jantari** [comment]
Ok the fix is out in v1.1.1 🚀

**Comment by jantari** [comment]
As it turns out 0979d45 wasn't really the final fix for this. I kept getting an indefinite hang with some executables like `detect_version_cs18_dp.exe` or `cs18_dphub_5_04_000.exe` on laptops like the L480 and L490, but not always. Sometimes it ran though just fine which made tracking this one down quite difficult.

That said, I had some more time to diagnose these cases today and 4941c63 should fix these problems for real. I unknowingly passed an extra trailing space to the commands being run, you can even make out in your screenshot that the file it's looking for is `USBC_FW_V373<SPACE>.exe`, which is why it wasn't found. The kerning may not be the best on that one.

This fix will ship in v1.1.2 which I'm preparing for a soon™️ launch :rocket:
