### ISSUE TITLE
Implement offline-repository

### ISSUE THREAD

**Issue by tboege** [jantari/LSUClient#17]
I would like to let lsuclient establish a offline repository. 
So after running get-lsupdate and save-lsuupdate (eventually with -createrepository path) from one computer, I would like to move $env:temp\LSUPDATE or path to a server share or directly to another computer.
Then, on another computer (on the same model)
1) $updates=get-lsupdate -repository \\server\share (or directory, eg. c:\localrep) No trafic should go to Lenovo, but all neccessary files should be available in the repository.
2) $updates|Save-lsuUpdate (should download  from the repository used in 1 - and still no trafic to Lenovo)

This improvement will make it possible to push well-known updates to multiple clients, and hopefully save some bandwidth to Lenovo. If I update multiple computers directly from Lenovo, I cannot test, if the updates LSUCLIENT installs is ok, and I cannot ensure, that all computers gets the same updates, because Lenovo could release new updates after the first computer is updates.

I would like to have one repository for each model, but other users might like to have one big repository, so it would be possible to avoid hosting multipe copies the same package for several different computer models. If it would be possible to mix models in the same repository, I would still be able to have only one model per repository by specify different repository for each model.

**Comment by jantari** [comment]
Hi, sorry for never responding to this.

I wasn't sure how many people were gonna use a feature like this, and it's not something I personally need yet - however after #20 I can see there's at least a couple people trying to use the module for offline-ish or at least more controlled driver deployments from a self-hosted repository.

The way I would want to do this is, the module should be able to create and read from the same repository format that Update Retriever uses - that way you could create a repository with LSUClient and then install from it with ThinInstaller, or you could create the repository with Update Retriever and point LSUClient to it. I think this level of compatibility is the ideal solution.

However, it'll also be a bit of work so I cannot make any promises yet on when it'll be done - or out for experimental testing,
just that I'm tackling this issue now.

**Comment by tboege** [comment]
I would just a like to add, that I appreciate your work on thins feature. I can see, you are doing some progress regarding preparing this feature.
I would prefer, that I could create the repository with LSUClient, but it is not that important. I  guess, I could use Update Retriever as well.
But I would like to  install software from the repository with LSUClient.

**Comment by jantari** [comment]
So, an update on this, it took quite a while because the module and `Get-LSUpdate` specifically was originally only designed to work with files and repositories that are hosted on a webserver and accessed via HTTP/S, but with custom (offline) repositories I feel like the expectation is very much that it should work with a filesystem directory path (local or UNC) as well - like the official tools.

That works now so I've pushed the progress so far and you can see and try it in the [feat-customrepository](https://github.com/jantari/LSUClient/tree/feat-customrepository) branch. When you download this branch the only user-facing difference is that there is a new `-Repository` parameter on `Get-LSUpdate` that can point to either your own webserver HTTP/S URL or to a filesystem directory repository.

Currently there is not yet a way to create an offline repository with the module, that's yet to come. You can either use a repository created with the Update Retriever tool or sort of custom finangle it by manually editing some XML files - but Update Retriever is probably easier for testing.

There is still some work and lots of testing to do, and maybe I'll have to change some things around again, but I'm feeling pretty good with the current implementation so if you want to give it a try please go ahead and share the results and problems if any.

Generally speaking the implementation is pretty flexible - you're able to mix-and-match online and offline packages, split packages between all kinds of locations (e.g. different offline repositories) etc. etc. by editing the XML definitions, but I am pretty sure once you do that to take advantage of these possibilities the repositories would not be valid/readable for the official Lenovo tools anymore and could only be used by LSUClient - but this is another thing I'll have to test more to confirm.

**Comment by jantari** [comment]
Well, it took a while but this feature is now shipping with LSUClient `1.3.0`

Custom package repositories, whether they are internal or offline or not, are now supported and can be pointed to with the `-Repository` parameter of `Get-LSUpdate`. You can hand-craft a repository structure, mirror Lenovos' or use "Update Retriever" to create and manage it.
