### ISSUE TITLE
script doesnt work

### ISSUE THREAD

**Issue by taaniellin** [jantari/LSUClient#23]
This command cant let download/install drivers or anything on my computer and even on remote pc, is there something i am doing it wrong or what? Can you help?

$updates = Get-LSUpdate -All | Where-Object { $_.IsApplicable -and -not $_.IsInstalled }
$updates = Save-LSUpdate -ShowProgress
$updates | Install-LSUpdate -Verbose
Also is there any mode i can make a log file input for that?

**Comment by jantari** [comment]
Sure, please run one command at a time, all of them with `-Verbose` added.
To the `Get-LSUpdate` command you can also add `-DebugLogFIle "C:\path\to\a\file.txt"` for an extra verbose log. The other commands don't support that parameter.

Also, which version of Windows and which computer model are you using?

**Comment by taaniellin** [comment]
Im running win10 2004, Model T470.
So basically there isnt any way to run that script from SCCM? i just need it to show the list, show list that is installing/not installed and thats it. so sad it cant be done with this module.

**Comment by jantari** [comment]
Sure it can be run from SCCM, we just need to find out why it's not working for you. Have you tried running it with the parameters I suggested and capturing the output to see what it's doing?

If you just want a list of what's installed or missing you only need

    Get-LSUpdate -All -Verbose

btw, since you're not going to download and install anything.

**Comment by taaniellin** [comment]
I'm trying to figure it out what im doing wrong..
Im running it from sccm sript section like this
$updates = Get-LSUpdate -All | Where-Object { $_.IsApplicable -and -not $_.IsInstalled }
$updates = Save-LSUpdate -ShowProgress
$updates | Install-LSUpdate -Verbose

When its running it doesnt load any information about whats applicable and whats not installed

**Comment by jantari** [comment]
It probably is loading that information, but you're never printing it to the console.

Try running just this:

    Get-LSUpdate -All -Verbose

as a script. That way the output of the command is not captured in a variable but printed to the console instead where you can see it.

**Comment by taaniellin** [comment]
Yeah that works, thanks.
So finding and printing i understand but for sccm when im deploying for another computer a285/a485 etc, those laptops cant run that correctly.  You Said to run every command one at a time, but i need to run them together, is there any issues with that maybe?

**Comment by jantari** [comment]
I have never used SCCM but I assume it is able to report the output of a PowerShell script/task back to you, so you'll just have to read the errors it spits out.

You also haven't said what precisely the problem is, you just say it "can't run" so it is impossible to make a suggestion for what could be wrong just based on that.

Could be anything from a typo to you not actually installing the module on the remote computer before trying to use it - I can't know, you should try getting help from someone who knows SCCM and can help you set up the script task correctly.

**Comment by taaniellin** [comment]
im sorry i didnt share specific problem.
The error exist when i have two where-object inject it like in this code 
$updates = Get-LSUpdate -All | Where-Object **{ $_.IsApplicable -and -not $_.IsInstalled }**
$updates = Save-LSUpdate -Verbose
$updates | Install-LSUpdate -Verbose 
 (it doesnt print anything out when 2 object are there, When i took one away, then the code run perfectly.)
Also wanted to know if i am running this command with save-lsupdate and install-lsupdate, why dont the save-lsupdate work then?
I have a script that install the module and then it runs other commands (get,save,install)
I am just trying to deploy that code perfectly and nothing more.
If its too hard or out of your reach you can close the issue then

**Comment by jantari** [comment]
Have you considered that, on the computer you're running this on, there just may be no updated missing (aka that are Applicable but not installed)?

In that case your `$updates` variable contains nothing, so there is nothing for `Save-LSUpdate` or `Install-LSUpdate` to do.

You should probably try this and see how many updates you get:

    [array]$updates = Get-LSUpdate -All
    Write-Output "$($updates.Count) updates found"
    [array]$updates = $updates| Where-Object { $_.IsApplicable -and -not $_.IsInstalled }
    Write-Output "$($updates.Count) updates needed, these will be downloaded and installed now"
    $updates = Save-LSUpdate -Verbose
    $updates | Install-LSUpdate -Verbose

**Comment by taaniellin** [comment]
Thank you very much, with that code i can get a respond from remote pc, but after that it doesnt do anything and waiting to insert package, the code is here:  55 updates in total
17 updates needed, these will be downloaded and installed now
cmdlet Save-LSUpdate at command pipeline position 1
Supply values for the following parameters:
Package:

**Comment by jantari** [comment]
Oh sorry that's because I made a syntax mistake in my last suggestion.

Since you don't get any output except for the `Write-Output` commands it seems that SCCM does not capture the verbose output stream. Try this again:

    [array]$updates = Get-LSUpdate -All -Verbose
    Write-Output "$($updates.Count) updates in total"
    [array]$updates = $updates | Where-Object { $_.IsApplicable -and -not $_.IsInstalled }
    Write-Output "$($updates.Count) updates needed, these will be downloaded and installed now"
    $updates | Save-LSUpdate -Verbose *>&1
    $updates | Install-LSUpdate -Verbose *>&1

btw, so far these have all been basic PowerShell troubleshooting steps, nothing specific to this module.
It would probably help you to familiarize yourself a bit with PowerShell scripting, not just because it's immensly useful in general, but also because it will enable you to quickly solve issues like these yourself wherever you might encounter them now or in the future.

**Comment by taaniellin** [comment]
Yeah im sorry also, i got basic knowledge on PS, but the code is working well now and other  Lenovo models had Nuget update problem( reason why it didnt allow to install LSUClient) Sorry for making troubles and really appreciate for your help.

**Comment by jantari** [comment]
No problem, I'm glad it's working as expected now.

If you encounter other problems while using the module, especially if you think it's a problem in the module itself, please open another issue.  :+1:
