### ISSUE TITLE
Support for caching outside of $env:temp

### ISSUE THREAD

**Issue by jwmoss** [jantari/LSUClient#30]
**Describe the solution you'd like**
In our environment, we have security requirements that block `.exe` files from being ran from `$env:temp`

**Describe alternatives you've considered**
I've did a find/replace for all `$env:temp` with `$env:userprofile` and I'm still running into issues. 

**Additional context**
NA.

**Comment by jantari** [comment]
That makes sense, I went with `$env:TEMP` initially because they _are_ temp files so it does make sense to store them there,
but I did not consider AppLocker policies etc.

Coincidentally though I've already been working on making this path configurable in preparation for implementing offline/custom repository support (issue #17), so this will likely be fixed in the next release - soon (tm)

**Comment by jwmoss** [comment]
Perfect, then that's another vote for me for me for [Issue #17](https://github.com/jantari/LSUClient/issues/17) that would solve this.

**Comment by jantari** [comment]
Version 1.2.3, which includes this fix, just released :tada:

You can use the new, optional `-ScratchDirectory` parameter of `Get-LSUpdate` to set a custom path for these temp files
