### ISSUE TITLE
Getting Remote server return 404 error.

### ISSUE THREAD

**Issue by Bhaumik9979** [jantari/LSUClient#36]
When I tried to execute Get-LSUpdate with administrator mode it's returning the below error. Can you please guide me on this issue?.
```
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\WindowsPowerShell\Modules\LSUClient\1.3.0\private\Save-PackageFile.ps1:46 char:9
+         $webClient.DownloadFile($SourceFile.AbsoluteLocation, $Downlo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebExceptio
```

**Comment by jantari** [comment]
If it is just one 404 error you get and the command otherwise works as expected it is most likely that a file is just missing in Lenovos repository. That does happen.

You can run `Get-LSUpdate` with the `-Verbose` parameter and it'll tell you what URLs it's trying to download. If the URL points to a file that doesn't exist you'll get a 404, but only Lenovo can fix that or you have to use your own repository.

**Comment by jantari** [comment]
It's been a while, have you had a chance to look into this any further? What computer model are you getting this 404 on (output of ``(gcim CIM_ComputerSystem).Model`) ?

**Comment by jantari** [comment]
Closing due to the lack of responses and the fact that some rare but reproducible 404s are "normal" for some computer models when accessing the official Lenovo repository, which is just sometimes missing a file. Typically this can be ignored, however should you ever get this error when accessing a self-hosted repository I'd advise trying to find and add the missing file(s) in there.
