### ISSUE TITLE
404 not found and getw10ver7.exe package error on some machines

### ISSUE THREAD

**Issue by isaacg123** [jantari/LSUClient#37]
**Describe the bug**
Getting the error below on a few lenovo machines. Sometimes a few updates are listed then followed by the exception error, but the error is the same either way.

**Error messages or Screenshots**
PS C:\WINDOWS\system32> Get-LSUpdate
Exception calling "DownloadFile" with "2" argument(s): "The remote server
returned an error: (404) Not Found."
At C:\Program Files\WindowsPowerShell\Modules\LSUClient\1.3.1\private\Save-Pack
ageFile.ps1:46 char:9
+         $webClient.DownloadFile($SourceFile.AbsoluteLocation, $Downlo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

WARNING: The command or file '%PACKAGEPATH%\getw10ver7.exe' could not be found
from 'C:\WINDOWS\TEMP\31uqabgy.3sc\yh2s4sbc.huz' and was not run

**Please complete the following information:**
 - Computer model: 81BH (LENOVO_MT_81BH_BU_idea_FM_ideapad 320-15IKB Touch)
 - Computer model: 90F10000US (LENOVO_MT_90F1_BU_LENOVO_FM_ideacentre 300S-08IHH)
 - Module version used: 1.3.1
 - Windows 10 build 19043

**Comment by jantari** [comment]
Hi, this is likely the same issue as #36 and we've also seen it before as part of #35 with Model `80VB`.

If you run `Get-LSUpdate` with the `-Verbose` parameter it'll tell you what URLs it's downloading, and for both models `81BH` and `90F1` the 404 error comes from same the URL https://download.lenovo.com/marketing/getw10ver7.exe which, if you check it manually, will also give a 404 because it doesn't seem to exist.

That file is just missing on Lenovos servers, probably an oversight on their end, but nothing we can fix unless you want to maintain your own repository. The error isn't fatal so the command contines and the warning you get later is when it's trying to run the `getw10ver7.exe` file (which doesn't exist because it couldn't be downloaded). Unless you work at Lenovo, I'd ignore this error as it's not caused by your network or LSUClient.

**Comment by isaacg123** [comment]
That's understandable. I was thinking I could modify my script to check for the error and report accordingly but when it gets to the point of the error the script just exits so the rest of the script doesn't execute. Is there a way to make Get-LSUpdate (or whatever it's triggering) not exit the script on error?  I assume this would also prevent any updates that come after the error from installing also, unless this error is only occuring after the installs are done.

**Comment by jantari** [comment]
It's a non-terminating error, so unless you've explicitly set `-ErrorAction` or `$ErrorActionPreference` to "Stop" in PowerShell it won't exit the cmdlet. If it exited then you also wouldn't get the `The command or file '%PACKAGEPATH%\getw10ver7.exe' could not be found` warning message later.

> I assume this would also prevent any updates that come after the error from installing also, unless this error is only occuring after the installs are done.

The error comes from `Get-LSUpdate`, so if you're in a situation where PowerShell really exits at that point then no updates would have been installed yet, yes. You'll have to look through your PowerShell settings to find out why it's exiting if that's the case.

**Comment by isaacg123** [comment]
Doh, I forgot I had a generic trap in there to capture errors and exit 2 (script failure for syncro so I get alerted). Commenting that out the script continues fine, thanks. I'll add an exception to ignore 404's.

**Comment by jantari** [comment]
Ah yes, that would explain it as well 😉
