### ISSUE TITLE
Intel graphics UHD 620 blocked

### ISSUE THREAD

**Issue by musklor** [jantari/LSUClient#49]
I use your script but an installation is blocked. I have to kill "installer.exe" process.

Package : n2hdr34w
Model : 20QG

https://download.lenovo.com/pccbbs/mobiles/n2hdr34w_2_.xml

Installer -s is not well interpreted?

**Comment by jantari** [comment]
There should be a log file from the installer at `$env:ProgramData\Intel\Logs\IntelGFX.log`. This is overwritten every time the installer starts so you'll have to check it right while the installer hangs.

It's also a 1.6 GB driver package so it might just take a while? How long did you let it run?

Can you install it manually by just running `installer.exe` and going through the GUI?

**Comment by musklor** [comment]
I waited 2 hours.
Manual install is OK.

**Comment by jantari** [comment]
Oh nevermind then. Does it still hang when you try installing it through LSUClient again? Anything in the log file then?

**Comment by musklor** [comment]
I'll watch tomorrow

**Comment by musklor** [comment]
OK, so the installer doesn't like to be in the c:\windows\temp folder

**Comment by musklor** [comment]
How can I specify a different folder?

**Comment by musklor** [comment]
Get-LSUpdate | install-LSUpdate -path xxxx ?

**Comment by jantari** [comment]
Yes

**Comment by musklor** [comment]
> Use `Install-LSUpdate -Path`
> 
> Could you share the part of the logfile with me that has the error or problem relating to the c:\windows\temp folder being an issue? I currently don't have a machine on hand to replicate this problem but I'd like to see if I could work around the issue inside LSUClient to prevent it in the future.

Sorry for my late answer.
My coworker saw the issue, and explained to me.
I'll try to reproduce.

**Comment by musklor** [comment]
Thank you for your script.
Do you have the same for dell drivers? I'm kidding. :)

**Comment by jantari** [comment]
Thanks for finding and linking that forum post, I was able to replicate the issue when running as the SYSTEM user.

No idea why Intel won't allow installations from that directory, or why their error window comes up even in silent `-s` mode 🤦 

But, installing from a different directory with `Install-LSUpdate -Path` did prevent the issue in my tests so that's an easy solution when running LSUClient as SYSTEM. For most regular user accounts, their TEMP directory is inside their user profile where Intel doesn't omplain about it so no change is needed.

For Dell, I have no personal experience but I've heard Dell Command Update (DCU) has a CLI that apparently works quite well!
