### ISSUE TITLE
Add success code 259

### ISSUE THREAD

**Issue by musklor** [jantari/LSUClient#50]
I think we could add the success code 259 into the Install-LSUpdate script.

ERROR_NO_MORE_ITEMS (259): No devices match the supplied driver or the target device is already using a better or newer driver than the driver specified for installation.

We could have less error.

https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/pnputil-return-values

'INF' {
                    $InfSuccessCodes = @(0, 259, 3010) + $PackageToProcess.Installer.SuccessCodes
                    $InstallCMD = "${env:SystemRoot}\system32\pnputil.exe /add-driver $($PackageToProcess.Installer.InfFile) /install"
                    $installProcess = Invoke-PackageCommand -Path $PackageDirectory -Command $InstallCMD

**Comment by jantari** [comment]
Thanks for the suggestion,

but I think when a user calls `Install-LSUpdate` the intent and expectation is to install that specific driver-package. So if the exit code indicates that the driver was _not_ installed then that constitutes a failure. Basically the desired outcome was not achieved.

Is this behavior causing you issues in a particular scenario or usecase? Are you seeing many failures with exit code 259?

**Comment by musklor** [comment]
For example, the lenovo DPR is an old driver, the same since 2019. So the log show 259 exit code. But in the batch file 259 exit code is a success one.

**Comment by musklor** [comment]
I made a test and I have an update who always want to be installed.

**Comment by jantari** [comment]
That is an issue, although a different one.

On what computer model is that happening? And can you post the output of `Get-LSUpdate -Verbose -Debug` you get on that machine?

**Comment by musklor** [comment]
And an annoying bug. Sometimes firmware ME is not installed and after update, no more ethernet.....
So I launch the script in the subfolder "misc" (without pause).

**Comment by musklor** [comment]
> That is an issue, although a different one.
> 
> On what computer model is that happening? And can you post the output of `Get-LSUpdate -Verbose -Debug` you get on that machine?

X1 yoga (20qg)

**Comment by jantari** [comment]
The problem is that the DPR utility package ( https://download.lenovo.com/pccbbs/mobiles/n2hwz12w_2_.xml ) checks for already being installed like this:

```
<DetectInstall>
  <_FileVersion>
    <File>%WINDOWS%\system32\LENOVO.DPRSVC.exe</File>
    <Version>1.0.0.14^</Version>
  </_FileVersion>
</DetectInstall>
```

so it looks for that file path, but that file is never installed there. On my test system, the file `LENOVO.DPRSVC.exe` is only installed to a directory like this `C:\Windows\System32\DriverStore\FileRepository\dprext.inf_amd64_xxxxxxxxxxxxxxxx\`.

This is why the DetectInstall check always fails for this package and why this update always wants to be installed. It's an error in the package definition / DetectInstall test.

You could download the package to an internal repository and fix the DetectInstall test in the XML yourself, or work around it / filter the package another way in PowerShell.

Does that answer your question?

**Comment by musklor** [comment]
I close the issue, thank you
