### ISSUE TITLE
Return values in Resolve-XMLDependencies

### ISSUE THREAD

**Issue by animentork** [jantari/LSUClient#55]
### Version

1.4.2

### Question

Hi,

While it's currently not a bug, it may have the potential to become one, so I only file this as a question.

In Resolve-XMLDependencies.ps1, you have this foreach loop in line 15:
`foreach ($XMLTREE in $XMLIN) {`

Every iteration can return a resulting $true or $false value, like in line 41:
`if ($subtreeresults -contains $false) { $false } else { $true  }`

Ergo, in theory, the function Resolve-XMLDependencies can return multiple values because of the foreach loop. The following parts of Get-LSUpdate.ps1, however, rely on the output being a single value, take lines 264-269:

```
[Nullable[bool]]$PackageIsApplicable = if ($NoTestApplicable) {
    $null
} else {
    Write-Verbose "Parsing dependencies for package: $($packageXML.Package.id) ($($packageXML.Package.Title.Desc.'#text'))"
    Resolve-XMLDependencies -XMLIN $packageXML.Package.Dependencies -TreatUnsupportedAsPassed:(-not $FailUnsupportedDependencies) -PackagePath $LocalPackageRoot
}
```

$PackageIsApplicable should only be $true or $false, never an array.

In the beginning, I wrote this is not a bug right now. This is due to the fact that the Dependencies and DetectInstall nodes only seem to have a single XMLTREE (like a single "And" or "Driver" node), and so the foreach loop only takes one iteration and the function only returns this single value. At least, I didn't find any examples to the contrary.

I would suggest either removing the foreach loop or handling multiple output values somehow in Resolve-XMLDependencies.ps1.

Also, I really admire your work and dedication to this project and worked on a heavily modified version of it myself, so I happen to know your code quite a bit by this time. And while my own version of Resolve-XMLDependencies sadly deviates to much by this point to be be of any use here, I hope I can support you with observations like these.

Thanks!

**Comment by animentork** [comment]
Ah, I understand now that you need the foreach loop for the recursive function calls and their ChildNodes and already handle their multiple values, but never return multiple values at the very first level.

Don't mind this question, closed!

**Comment by jantari** [comment]
Hi,

first of all thank you for reading the code! This one didn't turn out to be a bug, but it could've been, so thank you for taking the time to open the issue. Also, if you find that a code path is rather complex and takes a while to follow and understand, please feel free to submit a PR that just adds comments to it.

As you've commented, the function calls are recursive and each iteration evaluates its immediate childrens' results and returns only a single boolean "up" to the parent caller. Because the first XML node that is evaluated is the root `<Dependencies>` element, the evaluation of this element only ever returns one value - *unless* if there was a case where an XML had multiple `<Dependencies>` nodes. I find that to be sufficiently unlikely to not build special handling for it but I tested it anyway with an edited XML and the good news is that even if that did ever happen, this assignment:

https://github.com/jantari/LSUClient/blob/baed4d2d831590398b6519b8b860c175341b0964/public/Get-LSUpdate.ps1#L264

just fails with ``Cannot convert value "System.Object[]" to type "System.Nullable`1[System.Boolean]".`` and subsequently, because I enable StrictMode, this:

https://github.com/jantari/LSUClient/blob/baed4d2d831590398b6519b8b860c175341b0964/public/Get-LSUpdate.ps1#L304

fails with `The variable '$PackageIsApplicable' cannot be retrieved because it has not been set.`. These are non-terminating exceptions, so the malformed package is not returned and `Get-LSUpdate` continues just fine with the next.

Regarding you maintaining a modified version of LSUClient, is that because you need a specific feature that LSUClient doesn't currently offer? If so I'd like to look into whether it can be added so more people can benefit from it.
