### ISSUE TITLE
Support For Additional Dependency Types

### ISSUE THREAD

**Issue by ChrisKibble** [jantari/LSUClient#7]
The following are some additional dependency types that you may not have come across already:

_RegistryKey (see n1ora16w)
_Driver (see n1ndt23w, n1noi06w, n1nna04w)
_EmbeddedControllerVersion (see n1vuj21w)
_Coreq (see r0yvu27w)
_FileVersion (see n1vti07w)

**Comment by jantari** [comment]
I'm always looking to support more dependency types.

Most of these should be somewhat trivial, except for Coreq.
I've seen that before but didn't know what it was.
Do you know what that is and how to retrieve that information from within Windows or PowerShell?

I'll target to support the other types with version current+2, so 1.0.3/1.1.0/2.0.0 (I try to comply with SemVer)

If you could tell me what computer models you encountered these on that would also be helpful!

**Comment by jantari** [comment]
Support for the following additional dependency types:

_EmbeddedControllerVersion  
_FileExists  
_RegistryKey  
_OSLang  
_Driver

was added in v1.0.3 which is released now on GitHub and will come to the PSGallery shortly after

**Comment by keit999** [comment]
Could we get in contact. Need some info

**Comment by jantari** [comment]
Support for the following additional dependency types:

_RegistryKeyValue
_FileVersion

was added in v1.1.0 which is released now on GitHub and will come to the PSGallery shortly after.

_Coreq is trickier because it references another package, so I have to build a way to ensure packages get installed in a certain order and also communicate this to the user in a way that's understandable.

**Comment by jantari** [comment]
I had been leaving this issue open as a reminder for myself to implement support for the mentioned `_Coreq` dependency type, but it's been two years now and I don't have plans to get back to it in the near future either. I made an exploratory attempt on the [feat-coreqsupport](https://github.com/jantari/LSUClient/tree/feat-coreqsupport) branch for a while but never finished it.

It proved to be tricky to implement and hard to verify because I can't be sure how exactly `_Coreq` is supposed to behave / how it's treated by the official System Update. I thought it's just used to denote that certain packages have to be installed before others, but sometimes that's done with the usual `_Driver`, `_RegistryKey` or `_FileExists` etc. tests so I was never sure of that.

I also don't really see `_Coreq` anymore on more recent packages and I've never seen a package for which not supporting it has caused a problem.

So I'm closing this issue for housekeeping reasons, all other dependency types listed here have long been supported and `_Coreq` is a wontfix for the foreseeable future. If it makes a big comeback again maybe I'll have to reconsider.
