### ISSUE TITLE
Get-LSUpdate error: "An item with the same key has already been added."

### ISSUE THREAD

**Issue by IT360BE** [jantari/LSUClient#76]
### Version

1.5.2

### Computer Model

20S7S02200 

### Problem

Get-LSUpdate -Model $model -All -Verbose | Where-Object { $_.Installer.Unattended }

throws this error: 
Exception calling "Add" with "2" argument(s): "An item with the same key has already been added."

**Comment by jantari** [comment]
Yea, I noticed this error yesterday as well. lt is new in 1.5.2 - my bad.

It happens when multiple different packages for one computer have the same name which I didn't think could be the case.

The line that's failing isn't that important though so you should be able to just ignore it for now and I'll fix it in the next release.

Thank you for reporting it!

**Comment by swoonhusker1** [comment]
My install is running via Powershell App Deployment Toolkit and it looks like it is stuck and never gets the drivers-
![image](https://user-images.githubusercontent.com/47569583/225106233-c965192b-e44f-4179-ace5-ee736954a007.png)

I wonder if there is something I need to do in order to get it to continue.

When I run it in powershell ISE it does continue-
![image](https://user-images.githubusercontent.com/47569583/225106945-4e3e56c7-9cac-481c-bbf9-5156d981c325.png)

**Comment by swoonhusker1** [comment]
Looks like it's doing the same thing in our task sequence. I'm going to switch it back to copying the 1.5.1 version and re-image to make sure it's working again.

**Comment by jantari** [comment]
@swoonhusker1 Are you maybe setting `$ErrorActionPreference` to Stop in your script? That would make any script exit at the first error. But with the default setting of Continue it should print the error and .... continue 😄

**Comment by swoonhusker1** [comment]
I tried setting ErrorActionPreference to continue and it looks like it's still not working, but like I said if I run it in normal powershell it works fine, so I think it has something to do with Powershell App Deployment Toolkit (PSADT) that I don't understand. I'm going to set the script to install the 1.5.1 version for now.

**Comment by IT360BE** [comment]
> I tried setting ErrorActionPreference to continue and it looks like it's still not working, but like I said if I run it in normal powershell it works fine, so I think it has something to do with Powershell App Deployment Toolkit (PSADT) that I don't understand. I'm going to set the script to install the 1.5.1 version for now.

psappdeplykit is running in a big try catch loop... that is your issue. I don't think you can bypass those issues.

for processes I bypass bad exitcodes like this:
Execute-Process -FilePath "robocopy.exe" -Parameters "`"C:\Program Files (x86)\Adobe\Acrobat 2015\Acrobat`" `"C:\Windows\SysWOW64`" AcroCloudConnect.dll /R:0 /W:0 /LOG:$configToolkitLogDir\AcroCloudConnect.log" -PassThru -**IgnoreExitCodes '1'**

**Comment by jantari** [comment]
LSUClient 1.5.3 just released and fixes this. Thanks again for reporting it.
