### ISSUE TITLE
Export output of Get-LSUpdate to xml

### ISSUE THREAD

**Issue by IT360BE** [jantari/LSUClient#78]
We've exported Get-LSUpdate to xml for later use. We've also pre-downloaded all the drivers of our models on a central share to work with a PRD and Pilot release. We've used Install-LSUpdate -package % $(import-Clixml $filename%) -Path %CentralShare% but that's not working because you use objecttypes, and they are not exported by using  Export-Clixml.

You,ve provided a way to download all the files for another computer, it should be handy if you foresee also a way to export the parameter package, for Install-LSUpdate, to a file as well. This allows us to work 100% with your module + work with releases of driver packages.

Thanks in advance!

**Comment by jantari** [comment]
Supporting the deserialized objects from `Import-Clixml` as input is something I haven't had to do before so it's going to take a bit of research and lots of testing.

But to make sure I understand the usecase, why do you export the output from `Get-LSUpdate` for later? The problem I see with that approach is that the state of the computer or the driver repository could change in between when you export the `Get-LSUpdate` results and when you re-import and use them - for example if a driver got uninstalled on the computer, or a package updated in the repository in the meantime, the old exported results would no longer be accurate. I would generally recommend to run `Get-LSUpdate`  and `Install-LSUpdate` together so that the information is up to date.

I think it would help if you describe how you use the module currently.

**Comment by IT360BE** [comment]
> oblem I see with that approach is that the state of the computer or the driver repository could change in between when you export the `Get-LSUpdate` results and when you re-import and use them - for example if a driver got uninstalled on the computer, or a pack

We have around 1000 computers and 24 different models. Every night we run this command for every model, so 24 times:
$Packagedata = Get-LSUpdate -Model $model -All -Verbose | Where-Object { $_.Installer.Unattended } 	
$Packagedata | Save-LSUpdate -Path $Path_Temp -Verbose
$Packagedata | Export-Clixml $Package -Verbose -Confirm:$false -Force

We send out those driverpackages, via SCCM, to a pilot group of computers, after 7 days we send it to PRD. Doing this allows us to allign all the computers. We know that some drivers are not or no longer applicable... but it's the most robust approach. The alternative would be using the Lenovo Patch for SCCM wich cost 10$ per computer per month or working with Lenvo System update wich is hard to work with Maintenance Window.

**Comment by jantari** [comment]
LSUClient 1.6.0 should support this now, if you could test it again to confirm that would be great!
