### ISSUE TITLE
Run Without User Being Logged In

### ISSUE THREAD

**Issue by dylbrwn** [jantari/LSUClient#8]
Is there a way to get this module to run as SYSTEM and save to another folder other than user appdata? I would like to have this run on PCs during an SCCM Task Sequence. Unlike MDT, SCCM doesn't login as a user during OSD so I don't believe this module will work for that use case.

**Comment by jantari** [comment]
You can already specify a custom path for `Save-LSUpdate` and `Install-LSUpdate`.

Do note that you'll need to specify the same path for both commands or else `Install-LSUpdate` won't find the packages.

I don't have access to SCCM so I unfortunately cannot test this, but it has to be logged in with *some* user. If it's "NT AUHTORITY\SYSTEM" that shouldn't be a problem - I just checked, and the TEMP directory is `C:\WINDOWS\TEMP` when you are the SYSTEM user so that should work just fine. I'm not hardcoding a path to a users appdata, I'm just using the `TEMP` environment variable ($env:TEMP in PowerShell, %TEMP% in cmd) which happens to point into appdata for a regular user.

Is there a specific problem or error message you're seeing?

**Comment by jantari** [comment]
It's been two weeks and I'm pretty sure the module would run just fine through SCCM so I'm closing this issue.

Should you encounter a specific problem feel free to reopen or file a new issue with a detailed description of it.

**Comment by dylbrwn** [comment]
Yeah I appreciate it
