### ISSUE TITLE
Repeated installations of the same driver

### ISSUE THREAD

**Issue by SynMaki** [jantari/LSUClient#88]
### Version

1.5.5

### Computer Model

ALL

### Problem

Hey jantari,

I have been switching to 2 rounds for some time now.

The problem arises that drivers/firmware/bios updates, which have already been installed in the first round, want to be installed again in the second round.
Mostly this is not a problem, but with a Bios update this brought errors, they Bioserror.txt. On reboot the bios update was installed.

Also I attach other logs where the repetitive install shows up

### Additional context

[BiosError.txt](https://github.com/jantari/LSUClient/files/11403701/BiosError.txt)
[LSUClient.txt](https://github.com/jantari/LSUClient/files/11403702/LSUClient.txt)

**Comment by jantari** [comment]
It's very unfortunate that a BIOS update opens am error window even when it is run with `/verysilent`...

But, installing a BIOS update multiple times in a loop is unnecessary anyways because it will only finish installing at the next reboot or shutdown, which is also why it's showing up again in the eecond round. If you didn't reboot in between rounds the BIOS update is not actually fully installed yet.

What I do in my LSUClient script is delay BIOS updates until the last round. This saves some time as it's unnecessary to run the installer multiple times and it would avoid your issue too. This is the relevant snippet I use:

```powershell
# ...

 for ($i = 0; $i -lt $upd.Count; $i++) {
     if ($round -ne $maxRounds -and $upd[$i].Type -eq 'BIOS') {
         # Only install BIOS updates in the last round
         Write-Output "[ $(Get-Date -Format 'HH:mm:ss') | ROUND ${round} | Delayed installing BIOS update until last round! ]"
         continue
     }
     Write-Output "[ $(Get-Date -Format 'HH:mm:ss') | ROUND ${round} | Installing package $($i + 1 )/$($upd.Count) :  $($upd[$i].Title) ] "
     Install-LSUpdate -Package $upd[$i] -Verbose -Debug | Out-Default
 }

# ... 
```

**Comment by SynMaki** [comment]
Yeah, another bad package from lenovo. its like 99% of the times there is an issue, it is an issue with a lenovo package.

Thats a great idea, i will definetely try that. Thanks for that!

Howerver, is there some way i can prevent LSU from installing the same Drivers/Firmware in round 2, which has already been installed in round 1?
