### ISSUE TITLE
Model lookup failure

### ISSUE THREAD

**Issue by wgriffinArch** [jantari/LSUClient#95]
### Version

1.6.0

### Computer Model

21CCS3AJ00

### Problem

`PS C:\WINDOWS\system32> $Updates = Get-LSUpdate
Invoke-PackageCommand : Unable to find type [LSUClient.JobAPI].
At C:\Program Files\WindowsPowerShell\Modules\LSUClient\1.6.0\private\Get-WindowsVersion.ps1:12 char:18
+ ... CmdOutput = Invoke-PackageCommand -Path $env:SystemRoot -Executable " ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (LSUClient.JobAPI:TypeName) [Invoke-PackageCommand], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,Invoke-PackageCommand

WARNING: The repository 'https://download.lenovo.com/catalog' did not contain either a '21CC_Win10.xml' or 'database.xml' file to get packages from
No packages for computer model '21CC' could be retrieved from repository 'https://download.lenovo.com/catalog'
At C:\Program Files\WindowsPowerShell\Modules\LSUClient\1.6.0\public\Get-LSUpdate.ps1:159 char:13
+             throw "No packages for computer model '${Model}' could be ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No packages for...vo.com/catalog':String) [], RuntimeException
    + FullyQualifiedErrorId : No packages for computer model '21CC' could be retrieved from repository 'https://download.lenovo.com/catalog'`

**Comment by jantari** [comment]
Since https://download.lenovo.com/catalog/21CC_Win10.xml does actually exist there must have been a (temporary) network issue at the moment this script ran.

You can view more details about the last few errors in PowerShell with `$Error[0..2] | Select-Object * | Format-List *`. This will also show info about errors that were silenced.

For example, when you run `Get-LSUpdate -Model "22CC" -All` (model 22CC doesn't exist) you ge the same error, and then when you run `$Error[0..2] | Select-Object * | Format-List *` right after it will show, among other things:

    System.Management.Automation.MethodInvocationException: Exception calling "GetResponse" with "0" argument(s):
    "The remote server returned an error: (404) Not Found."

A 404 error is expected in this case. For you it might have been a timeout or a 403 if access to the URL was forbidden by a proxy etc.

**Comment by jantari** [comment]
Were you able to reproduce the problem and/or get any additional information about the error like I've described above?

**Comment by jantari** [comment]
Closing because it's unlikely to be an issue in LSUClient and no response
