### ISSUE TITLE
Get-LSUpdate misses network drivers on multiple systems

### ISSUE THREAD

**Issue by LinkSlayer64** [jantari/LSUClient#97]
### Version

1.6.0

### Computer Model

10AF0003US, 10M8S0L800, (others I cannot grab at this moment.)

### Problem

Both of the systems I listed have newer network drivers available when I manually browse for drivers on the Lenovo support site, but they do not get pulled up when running Get-LSUpdate.
on the 10M8:
![image](https://github.com/jantari/LSUClient/assets/5333706/fb08c44a-7614-4b5f-9a9c-33d42f7ffd42)
![image](https://github.com/jantari/LSUClient/assets/5333706/a91a9127-c1a6-47b7-9be2-728702e450af)

Even running with -All does not give me it:

![image](https://github.com/jantari/LSUClient/assets/5333706/3e9df689-fb4a-4f34-af9a-cf4d86297868)

Same for the 10AF:

![image](https://github.com/jantari/LSUClient/assets/5333706/5260da6e-27c4-4da6-af33-bfc0160ee820)
![image](https://github.com/jantari/LSUClient/assets/5333706/40f578f9-b84b-4d9e-ba67-3c17eccd9cbe)
![image](https://github.com/jantari/LSUClient/assets/5333706/885afbc9-f2c0-4903-b9ef-edcf6cb8e74e)

If I'm just doing something wrong, I'm terribly sorry, just trying to work my way through a pretty badly managed network I inherited. Let me know if I can provide any additional info. Thanks.

**Comment by jantari** [comment]
It looks like in the case of the Realtek driver on the 10M8 it was returned, at least with `-All`:

![grafik](https://github.com/jantari/LSUClient/assets/25607767/4beffbaf-1e10-43e3-9821-a053941fb847)

if it was not returned without `-All` then it was probably either detected as not applicable or already installed. To debug why you can run `Get-LSUpdate -Verbose -Debug` which shows the whole detection process in all its detail.

---

But in the case of the Intel driver on the 10AF, it seems like Lenovo really didn't include it in their driver listing for the 10AF ( https://download.lenovo.com/catalog/10AF_win10.xml ). If you have a support contract with them you can ask them to add it, but it's possible they won't change it because the site for that PC / driver says it is out of support:

![grafik](https://github.com/jantari/LSUClient/assets/25607767/fe2dd4a0-b97a-463d-b1ce-09a706987d58)

https://pcsupport.lenovo.com/us/en/products/desktops-and-all-in-ones/thinkcentre-m-series-desktops/thinkcentre-m93z/10af/downloads/ds542693-intel-lan-driver-for-windows-10-desktop-workstation?category=Networking%3A%20LAN%20%28Ethernet%29

Other ideas are you could either:

1. Download the drivrer manually and add it to an [internal driver repository](https://jantari.github.io/LSUClient-docs/docs/topics/self-hosted-repositories/) or
2. Get the driver from a PC model that does still have it associated with it in Lenovos' repository, such as the ThinkStation P330 2nd Gen (`30CY`) with a command like:
    ```powershell
    Get-LSUpdate -Model "30CY" -All -NoTestApplicable -NoTestInstalled -NoTestSeverityOverride | Where Title -like "*Intel*lan*"
    ```
    You would run this command *in addition* to your regular install logic, just to get this one extra driver. Essentially just a trick to get the package from somewhere else.

**Comment by jantari** [comment]
Does that answer your question?

**Comment by LinkSlayer64** [comment]
Terribly sorry, I got sick last week - yes it did, it also informed some future decisions we may make as we're looking into Modern Driver Management, and I'd imagine that probably uses the same repositories you pull from.

Also sorry about missing that first driver, teach me not to work at 2AM.


Thank you again for the workaround!

**Comment by jantari** [comment]
No problem, I'll close this one because there's not much I can do on the side of LSUClient, but feel free to open more issues if you run into problems.
